export const inputs = [
    {
        classes: "shop-cart__form",
        id: "name",
        value: "",
        textLabel: "Имя*",
        name: "name",
        type: "text",
        required: true,
    },
    {
        classes: "shop-cart__form",
        id: "middle-name",
        value: "",
        textLabel: "Отчество",
        name: "middleName",
        type: "text",
        required: false,
    },
    {
        classes: "shop-cart__form",
        id: "city",
        value: "",
        textLabel: "Город*",
        name: "city",
        type: "text",
        required: true,
    },
    {
        classes: "shop-cart__form",
        id: "email",
        value: "",
        textLabel: "E-mail*",
        name: "email",
        type: "email",
        required: true,
    },
    {
        classes: "shop-cart__form",
        id: "phone",
        value: "",
        textLabel: "Телефон*",
        name: "phone",
        type: "tel",
        required: true,
    },
]